A:
	cat Ainput.txt | pypy A.py
B:
	cat Binput.txt | pypy B.py
C:
	cat Cinput.txt | pypy C.py
D:
	cat Dinput.txt | pypy D.py
D2:
	cat Dinput_2.txt | pypy D.py
Dcpp:
	g++ -o D.out D.cpp
	./D.out
E:
	cat Einput.txt | pypy E.py
E2:
	cat Einput_2.txt | pypy E.py
F:
	cat Finput.txt | pypy F.py
G:
	cat Ginput.txt | pypy G.py
H:
	cat Hinput.txt | pypy H.py
I:
	cat Iinput.txt | pypy I.py
J:
	cat Jinput.txt | pypy J.py
K:
	cat Kinput.txt | pypy K.py
L:
	cat Linput.txt | pypy L.py
M:
	cat Minput.txt | pypy M.py