A:
	cat Ainput.txt | python A.py
B:
	cat Binput.txt | python B.py
C:
	cat Cinput.txt | python C.py
D:
	cat Dinput.txt | python D.py
D2:
	cat Dinput_2.txt | python D.py
Dcpp:
	g++ -o D.out D.cpp
	./D.out
E:
	cat Einput.txt | python E.py
E2:
	cat Einput_2.txt | python E.py
F:
	cat Finput.txt | python F.py
G:
	cat Ginput.txt | python G.py
H:
	cat Hinput.txt | python H.py