A:
	cat Ainput.txt | python A.py
B:
	cat Binput.txt | python B.py
C:
	cat Cinput.txt | python C.py
D:
	cat Dinput.txt | python D.py
D2:
	cat Dinput_2.txt | python D.py
E:
	cat Einput.txt | python E.py
E2:
	cat Einput_2.txt | python E.py
F:
	cat Finput.txt | python F.py
F2:
	cat Finput_2.txt | python F.py